from typing import Protocol

from app.domain.entities.conversation import Conversation


class ConversationRepository(Protocol):
    async def get_by_id(self, conversation_id: str) -> Conversation | None: ...
    async def save(self, conversation: Conversation) -> None: ...
    async def list_recent(self, limit: int = 20) -> list[Conversation]: ...
    async def delete(self, conversation_id: str) -> None: ...
